use empresa;
# INNER JOIN
SELECT F.NOME, T.NUMERO
	FROM FUNCIONARIOS AS F
    INNER JOIN TELEFONES AS T
		ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO;
        
        

# LEFT JOIN
SELECT F.NOME, T.NUMERO
	FROM FUNCIONARIOS AS F
    LEFT JOIN TELEFONES AS T
		ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO;